let @a = $HOME . "/vimrc_repo/srcs/"
let @b = $HOME . "/vimrc_repo"

"srcs holds all the includes (.vim)
let srcs = [
  \"stdheader.vim",
  \"wolf3d.vim",
  \"c.vim",
  \"cpp.vim"
  \]

for src in srcs
	exec "source " . @a . src
endfor

syntax on
set number
set norelativenumber
set wrap
set matchtime=10
set ruler
set cc=80
set cul
"Make the current line highlighted"
hi CursorLine term=none cterm=none ctermbg=0

function Is_new_file()
	let myfile = expand('%:p')
	if filereadable(myfile)
		return 0
	else
		return 1
	endif
endfunction

function Skeletons()
	if (Is_new_file())
		let extension = expand('%:e')
		if (extension == "hpp")
			call Skeleton_hpp()
		elseif (extension == "h")
			call Skeleton_h()
		elseif (extension == "cpp")
			call Skeleton_cpp()
		elseif (extension == "c")
			call Skeleton_c()
		endif
	endif
endfunction

function LineDown()
	execute "normal! ddp"
	echo "lol"
endfunction

"space will select a word in visual mode"
map <space> viwye<right>
"put a whole line down"
map - ddp
"put a whole line up"
map _ ddkkp
"Y behaves like D"
map Y y$
silent call Skeletons()

